### ISSUE TITLE
Console: integration and optimisation

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb-console#8]
_This issue was originally posted by @haikalpribadi  on 2018-04-09 17:11_.

Why:
Grakn functions are exposed through different executables - some through `grakn`, some through `graql`, and some others through the KGMS console.
How:
Merge all console interfaces into one grakn-[core|kgms]-console.jar

This issue needs graknlabs/grakn#3087, needs graknlabs/console#7, needs graknlabs/grakn#3581, needs graknlabs/grakn#3743, needs graknlabs/grakn#3798, needs graknlabs/grakn#3807, needs graknlabs/grakn#3868, needs graknlabs/grakn#3871

**Comment by lolski** [comment]
The main goal of this issue has been implemented: unify different console interfaces into one (ie., into TypeDB Console).

However, I am keeping this issue open and moving them to Active, since the comments have more proposals regarding the management of TypeDB Cluster. We should take these comments and move them into a new issue dedicated to TypeDB Cluster management.
